
# Workflow to auto merge PRs

name: Auto Merge PR

on:
  pull_request:
    types: [labeled]
    
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Auto Merge PR
        uses:
          repo: pascalgn/automerge-action
          ref: v0.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
          MERGE_LABELS: automerge
          MERGE_METHOD: squash
          MERGE_DELETE_BRANCH: true

# Path: .github\workflows\auto-merge-pr.yml

